pub const CUDA_SUCCESS: i32 = 0;
pub const CUDA_ERROR_INVALID_VALUE: i32 = 1;
pub const CUDA_ERROR_OUT_OF_MEMORY: i32 = 2;
pub const CUDA_ERROR_NOT_INITIALIZED: i32 = 3;
pub const CUDA_ERROR_LAUNCH_FAILED: i32 = 700;
pub const CUDA_ERROR_ILLEGAL_ADDRESS: i32 = 700;
pub const CUDA_ERROR_INVALID_PITCH_VALUE: i32 = 703;

pub fn describe(code: i32) -> &'static str {
    match code {
        CUDA_SUCCESS => "CUDA_SUCCESS",
        CUDA_ERROR_INVALID_VALUE => "CUDA_ERROR_INVALID_VALUE",
        CUDA_ERROR_OUT_OF_MEMORY => "CUDA_ERROR_OUT_OF_MEMORY",
        CUDA_ERROR_NOT_INITIALIZED => "CUDA_ERROR_NOT_INITIALIZED",
        CUDA_ERROR_LAUNCH_FAILED => "CUDA_ERROR_LAUNCH_FAILED",
        CUDA_ERROR_INVALID_PITCH_VALUE => "CUDA_ERROR_INVALID_PITCH_VALUE",
        _ => "UNKNOWN_CUDA_ERROR",
    }
}
