//! **Adapter Toolkit v2** — a declarative layer *on top of* the v1
//! model-adapter system (`crate::model_adapters`).
//!
//! The toolkit lets a model be described by a small YAML/JSON
//! document instead of a hand-written Rust adapter. It is a strict
//! addition: it never modifies v1, never touches the runtime core
//! or the graph builders, and never generates Rust code. A v2
//! adapter is a v1 adapter *parameterised by data* — see
//! [`generator::GeneratedAdapter`].
//!
//! Pipeline:
//!
//! ```text
//!   .yaml/.json  ──dsl──▶  AdapterDsl
//!   AdapterDsl   ──spec─▶  ResolvedAdapterSpec   (Part 3 IR + Part 5 catalog)
//!   spec         ──gen──▶  GeneratedAdapter      (impl AteniaModelAdapter)
//!   adapters     ──reg──▶  AdapterRegistry       (v2-first, v1-fallback)
//! ```
//!
//! **Parts 2–5** (DSL, generator, registry, pattern normalisation)
//! live here today. Parts 6–9 (validation, introspection, CLI,
//! auto-detection) extend the same module.

pub mod dsl;
pub mod generator;
pub mod inspect;
pub mod introspect;
pub mod registry;
pub mod spec;
pub mod validate;

pub use dsl::AdapterDsl;
pub use generator::GeneratedAdapter;
pub use inspect::{inspect_model_dir, InspectionReport};
pub use introspect::{describe_adapter, describe_spec};
pub use registry::{AdapterRegistry, AdapterResolution};
pub use spec::{
    AttentionKind, FeatureSet, KvHeadsResolved, ResolvedAdapterSpec, ResolvedOverride,
    ResolvedTokenizer, RopeKind,
};
pub use validate::{validate, ValidationReport};

use std::path::Path;

/// `atenia load <file>` — parse a DSL file, validate it, build the
/// v2 adapter, and return the summary report. Never runs generation.
///
/// The pipeline is the toolkit contract end to end: file → DSL →
/// `validate` → `ResolvedAdapterSpec` → `GeneratedAdapter` →
/// `describe_adapter`. Any failure is a typed [`ToolkitError`].
pub fn run_load(path: &Path) -> Result<String, ToolkitError> {
    let dsl = AdapterDsl::from_file(path)?;
    run_load_dsl(&dsl, false)
}

/// `atenia debug <file>` — same as [`run_load`] but emits the
/// verbose report (v1 capabilities + GGUF→HF tensor-name sample)
/// and prints any validation warnings.
pub fn run_debug(path: &Path) -> Result<String, ToolkitError> {
    let dsl = AdapterDsl::from_file(path)?;
    run_load_dsl(&dsl, true)
}

/// Shared `load`/`debug` body: validate, generate, describe.
fn run_load_dsl(dsl: &AdapterDsl, verbose: bool) -> Result<String, ToolkitError> {
    let report = validate(dsl);
    // Fail loud on blocking errors before constructing anything.
    report.clone().into_result()?;

    let spec = ResolvedAdapterSpec::resolve(dsl)?;
    let adapter = GeneratedAdapter::from_spec(spec)?;

    let mut out = describe_adapter(&adapter, verbose);
    if !report.warnings.is_empty() {
        out.push_str("\n  warnings:\n");
        for w in &report.warnings {
            out.push_str(&format!("    ! {w}\n"));
        }
    }
    out.push_str("\n  status          : OK (adapter constructed; generation not run)\n");
    Ok(out)
}

/// `atenia inspect <dir>` — auto-detect a model directory and emit
/// a YAML DSL plus a resolved-spec preview. The emitted YAML is
/// guaranteed to be loadable by [`run_load`].
pub fn run_inspect(dir: &Path) -> Result<String, ToolkitError> {
    let report = inspect_model_dir(dir)?;
    // Self-check: the generated DSL must validate, or `inspect`
    // would emit something `load` rejects.
    validate(&report.dsl).into_result()?;
    let spec = ResolvedAdapterSpec::resolve(&report.dsl)?;

    let yaml = report.dsl.to_yaml()?;
    let mut out = String::new();
    out.push_str("# Adapter Toolkit v2 — generated by `atenia inspect`\n");
    out.push_str("# This YAML is loadable directly with `atenia load`.\n");
    // Auto-detection notes go in the YAML header as comments so the
    // file stays valid YAML and the limitations travel with it.
    for note in &report.notes {
        out.push_str("#\n");
        for line in wrap_comment(note) {
            out.push_str(&format!("# note: {line}\n"));
        }
    }
    out.push('\n');
    out.push_str(&yaml);
    out.push('\n');
    out.push_str(&describe_spec(&spec));
    Ok(out)
}

/// Wrap a long note into ~72-column lines for the YAML comment
/// header. Pure formatting — no semantic effect.
fn wrap_comment(text: &str) -> Vec<String> {
    let mut lines = Vec::new();
    let mut line = String::new();
    for word in text.split_whitespace() {
        if !line.is_empty() && line.len() + 1 + word.len() > 72 {
            lines.push(std::mem::take(&mut line));
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    if !line.is_empty() {
        lines.push(line);
    }
    lines
}

/// The single error type for every Adapter Toolkit v2 operation.
/// All variants carry an owned, human-readable message — the
/// toolkit is a developer-facing tool, so messages favour clarity
/// over machine structure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ToolkitError {
    /// The DSL document is not valid YAML/JSON, or does not match
    /// the [`AdapterDsl`] schema (includes unknown-field typos).
    Parse(String),
    /// A filesystem error reading a DSL file.
    Io(String),
    /// The DSL file extension is not `.yaml`, `.yml`, or `.json`.
    UnsupportedExtension(String),
    /// The DSL is structurally valid but cannot be resolved to a v1
    /// family / adapter (unknown family, unknown architecture, an
    /// inconsistent `kv_heads` keyword, …).
    Resolution(String),
    /// The resolved spec failed a declarative validation rule
    /// (Part 6).
    Validation(String),
}

impl std::fmt::Display for ToolkitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ToolkitError::Parse(m) => write!(f, "adapter DSL parse error: {m}"),
            ToolkitError::Io(m) => write!(f, "adapter DSL I/O error: {m}"),
            ToolkitError::UnsupportedExtension(e) => write!(
                f,
                "adapter DSL: unsupported file extension `{e}` (expected .yaml, .yml or .json)"
            ),
            ToolkitError::Resolution(m) => write!(f, "adapter DSL resolution error: {m}"),
            ToolkitError::Validation(m) => write!(f, "adapter DSL validation error: {m}"),
        }
    }
}

impl std::error::Error for ToolkitError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn error_display_is_prefixed_per_variant() {
        assert!(ToolkitError::Parse("x".into())
            .to_string()
            .contains("parse error"));
        assert!(ToolkitError::Resolution("x".into())
            .to_string()
            .contains("resolution error"));
        assert!(ToolkitError::UnsupportedExtension("toml".into())
            .to_string()
            .contains("toml"));
    }

    /// End-to-end smoke across Parts 2–4: DSL text → registry
    /// entry → v2 resolution.
    #[test]
    fn dsl_to_registry_end_to_end() {
        use crate::model_adapters::{ModelFormat, ModelMetadata};

        let dsl = AdapterDsl::from_str(
            "family: qwen\narchitecture: Qwen2ForCausalLM\ntokenizer:\n  eos_tokens: [151643]\n",
            true,
        )
        .expect("dsl parses");

        let mut registry = AdapterRegistry::new();
        registry
            .register_dsl("qwen-example", &dsl)
            .expect("registers");

        let resolution = registry.resolve(&ModelMetadata {
            architecture: "Qwen2ForCausalLM",
            model_type: Some("qwen2"),
            format: ModelFormat::HfSafetensors,
        });
        match resolution {
            AdapterResolution::V2 { name, adapter } => {
                assert_eq!(name, "qwen-example");
                assert_eq!(adapter.base_id(), "qwen2");
                assert_eq!(
                    adapter.spec().tokenizer.eos_tokens,
                    Some(vec![151643])
                );
            }
            _ => panic!("expected v2 resolution"),
        }
    }

    /// Every shipped example under `config/adapters/` must load
    /// cleanly through the full `atenia load` pipeline — this is
    /// the Part 10 guarantee that the examples "work directly".
    #[test]
    fn shipped_example_adapters_all_load() {
        for name in ["llama", "qwen", "gemma", "phi", "mistral"] {
            let path = std::path::PathBuf::from(format!("config/adapters/{name}.yaml"));
            let report = run_load(&path)
                .unwrap_or_else(|e| panic!("example {name}.yaml must load: {e}"));
            assert!(
                report.contains("status          : OK"),
                "example {name}.yaml report missing OK status"
            );
        }
    }

    /// `run_debug` on the advanced Phi example must surface the
    /// verbose sections.
    #[test]
    fn debug_on_phi_example_is_verbose() {
        let path = std::path::PathBuf::from("config/adapters/phi.yaml");
        let report = run_debug(&path).expect("phi.yaml debugs");
        assert!(report.contains("v1 capabilities"));
        assert!(report.contains("tensor-name sample"));
    }
}
